const Review = require("../models/Review");
const PDFDocument = require("pdfkit");

// ==============================
// Get All Reviews
// ==============================
const getReviews = async (req, res) => {
  try {
    const reviews = await Review.find().sort({ createdAt: -1 });

    res.json(reviews);
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Failed to fetch reviews",
    });
  }
};

// ==============================
// Delete Review
// ==============================
const deleteReview = async (req, res) => {
  try {
    const { id } = req.params;

    const review = await Review.findById(id);

    if (!review) {
      return res.status(404).json({
        message: "Review not found",
      });
    }

    await Review.findByIdAndDelete(id);

    res.json({
      message: "Review deleted successfully",
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Failed to delete review",
    });
  }
};

// ==============================
// Export Review PDF
// ==============================
const exportPDF = async (req, res) => {
  try {
    const { id } = req.params;

    const review = await Review.findById(id);

    if (!review) {
      return res.status(404).json({
        message: "Review not found",
      });
    }

    const doc = new PDFDocument({
      margin: 50,
      size: "A4",
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${review.repository}-PR-${review.pullRequest}.pdf`
    );

    doc.pipe(res);

    // ---------------- Header ----------------

    doc
      .fontSize(24)
      .fillColor("#111827")
      .text("CodeSentinel", {
        align: "center",
      });

    doc.moveDown(0.3);

    doc
      .fontSize(16)
      .fillColor("#555555")
      .text("AI Pull Request Review Report", {
        align: "center",
      });

    doc.moveDown(2);

    // ---------------- Repository Info ----------------

    doc
      .fontSize(14)
      .fillColor("black")
      .text(`Repository: ${review.repository}`);

    doc.text(`Pull Request: #${review.pullRequest}`);

    doc.text(
      `Date: ${new Date(
        review.createdAt
      ).toLocaleString()}`
    );

    doc.moveDown();

    // ---------------- Overall ----------------

    doc
      .fontSize(18)
      .fillColor("#1f2937")
      .text("Overall Assessment");

    doc.moveDown(0.5);

    doc.fontSize(13);

    doc.text(
      `Overall Score: ${review.overallScore}/100`
    );

    doc.text(
      `Security: ${review.securityScore}/10`
    );

    doc.text(
      `Performance: ${review.performanceScore}/10`
    );

    doc.text(
      `Maintainability: ${review.maintainabilityScore}/10`
    );

    doc.text(
      `Readability: ${review.readabilityScore}/10`
    );

    doc.text(
      `Risk Level: ${review.riskLevel}`
    );

    doc.moveDown();

    // ---------------- Summary ----------------

    doc
      .fontSize(18)
      .text("Executive Summary");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor("#444444")
      .text(review.summary);

    doc.moveDown();

    // ---------------- Issues ----------------

    doc
      .fontSize(18)
      .fillColor("black")
      .text("Findings");

    doc.moveDown();

    review.issues.forEach((issue, index) => {
      doc
        .fontSize(14)
        .fillColor("#111827")
        .text(`${index + 1}. ${issue.severity}`);

      doc
        .fontSize(12)
        .fillColor("#444444")
        .text(`Issue: ${issue.message}`);

      doc
        .fillColor("#15803d")
        .text(
          `Suggested Fix: ${issue.suggestion || "N/A"}`
        );

      doc.moveDown();
    });

    // ---------------- Footer ----------------

    doc.moveDown();

    doc
      .fontSize(11)
      .fillColor("#777777")
      .text(
        "Generated by CodeSentinel AI",
        {
          align: "center",
        }
      );

    doc.text(
      "Powered by Groq Llama 3.3 70B",
      {
        align: "center",
      }
    );

    doc.end();
  } catch (error) {
    console.log(error);

    res.status(500).json({
      message: "Failed to generate PDF",
    });
  }
};

module.exports = {
  getReviews,
  deleteReview,
  exportPDF,
};